apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: payment-settlement
  name: payment-settlement
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: payment-settlement
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-settlement
    spec:
      containers:
      - image: dsdebayan/payment-settlement:0.0.1-RELEASE #CHANGE
        imagePullPolicy: IfNotPresent
        name: payment-settlement
        env:
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
#          - name: SPRING_CLOUD_GCP_TRACE_ENABLED
#            value: "true"
          - name: RDS_HOSTNAME
            value: mysql
#          - name: SPRING_PROFILES_ACTIVE
#            value: kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: payment-settlement
  name: payment-settlement
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8002 #CHANGE
    protocol: TCP
    targetPort: 8002 #CHANGE
  selector:
    app: payment-settlement
  sessionAffinity: None #CHANGE
  type: NodePort